import Link from "next/link"

function Navbar() {
  return (
    <nav className="sticky top-0 z-50 w-full flex items-center justify-between px-6 md:px-8 h-14 backdrop-blur-sm"
      style={{ background: "rgba(10,15,26,0.9)", borderBottom: "1px solid var(--border)" }}>
      <Link href="/">
        <span className="text-base font-bold tracking-[3px]" style={{ fontFamily: '"Space Grotesk", sans-serif', color: "var(--accent)" }}>
          MERIDIAN
        </span>
      </Link>
    </nav>
  )
}

export default function TermsPage() {
  return (
    <div style={{ background: "var(--background)", color: "var(--text-primary)" }}>
      <Navbar />
      <main className="max-w-3xl mx-auto px-6 md:px-8 py-16 space-y-8">
        <div>
          <p className="text-xs mb-2" style={{ fontFamily: '"IBM Plex Mono", monospace', color: "var(--text-muted)" }}>
            Last updated: March 27, 2026
          </p>
          <h1 className="text-4xl font-bold" style={{ fontFamily: '"Space Grotesk", sans-serif' }}>
            Terms of Service
          </h1>
        </div>

        {[
          {
            h: "1. Service",
            p: "Meridian is an AI-powered personal operating system developed and operated by ChimeStream B.V. (Rotterdam, Netherlands). By using Meridian, you agree to these terms.",
          },
          {
            h: "2. Account",
            p: "Phase 1 is a private single-user instance. You are responsible for maintaining the confidentiality of your login credentials. Notify us immediately at hello@chimestream.com if you suspect unauthorized access.",
          },
          {
            h: "3. Acceptable use",
            p: "You agree to use Meridian for lawful personal productivity purposes only. You may not: attempt to reverse engineer the service, scrape data beyond normal use, share access credentials, or use the service for commercial purposes without prior written consent.",
          },
          {
            h: "4. Data ownership",
            p: "You own your data. We hold it on trust for you. You can export or delete it at any time. We do not claim any rights to your personal data, habits, goals, or any content you enter.",
          },
          {
            h: "5. AI-generated content",
            p: "The AI morning brief and pattern analysis are generated by Claude (Anthropic) based on your data. This content is informational only and does not constitute professional advice (medical, financial, psychological, or otherwise). You are responsible for your own decisions.",
          },
          {
            h: "6. Service availability",
            p: "Meridian is provided as-is during Phase 1 beta. We aim for 99% uptime but do not guarantee it. Planned maintenance will be communicated via Telegram when possible.",
          },
          {
            h: "7. Limitation of liability",
            p: "ChimeStream B.V. is not liable for any indirect, incidental, or consequential damages arising from use of Meridian. Our total liability for any claim is limited to €0 (Phase 1 is free).",
          },
          {
            h: "8. Changes",
            p: "We may update these terms as the service evolves. Continued use constitutes acceptance of updated terms. We'll notify you via email for material changes.",
          },
          {
            h: "9. Governing law",
            p: "These terms are governed by Dutch law. Disputes are subject to the exclusive jurisdiction of the courts in Rotterdam, Netherlands.",
          },
          {
            h: "10. Contact",
            p: "Questions about these terms: hello@chimestream.com",
          },
        ].map((section) => (
          <div key={section.h}>
            <h2 className="text-2xl font-semibold mb-3" style={{ fontFamily: '"Space Grotesk", sans-serif' }}>
              {section.h}
            </h2>
            <p className="text-base leading-relaxed" style={{ color: "var(--text-secondary)", lineHeight: "1.8" }}>
              {section.p}
            </p>
          </div>
        ))}
      </main>
    </div>
  )
}
